=== bryan-brancotte/projetgl-2008/doc/archives/XML/tests/testschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Olivier (none) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Station">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IDStation"/>
				<xs:element ref="ServiceStation"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ServicesList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ServiceStation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ID" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ID"/>
				<xs:element ref="Name"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Network">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ServicesList"/>
				<xs:element ref="Station"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="svKey">
			<xs:selector xpath="ServicesList/Service"/>
			<xs:field xpath="ID"/>
		</xs:key>
		<xs:keyref refer="svKey" name="refSvKey">
			<xs:selector xpath="Station/ServiceStation/ID"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="Name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IDStation">
		<xs:simpleType>
			<xs:restriction base="xs:byte"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ID">
		<xs:simpleType>
			<xs:restriction base="xs:byte"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== bryan-brancotte/projetgl-2008/doc/archives/XML/tests/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\olivier\Documents\Altova\XMLSpy2008\Examples\testschema.xsd">
	<ServicesList>
		<Service>
			<ID>1</ID>
			<Name>bla bla bla</Name>
		</Service>
		<Service>
			<ID>2</ID>
			<Name>pipi</Name>
		</Service>
	</ServicesList>
	<Station>
		<IDStation>
1
</IDStation>
		<ServiceStation>
			<ID>2</ID>
			<ID>1</ID>
		</ServiceStation>
	</Station>
</Network>
