=== bryan-brancotte/projetgl-2008/doc/XML/NetworkGL2008.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Olivier (none) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Definition d'un service aux clients (id unique) -->
	<xs:element name="Service">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ID" type="xs:int"/>
				<xs:element name="ShortDescription" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Definition d'une station (id unique).
          Cle etrangere vers les services (au niveau de Network) -->
	<xs:element name="Station">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element name="ID" type="xs:int"/>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="StationServicesList">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="ID" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Section ("Troncon") : Une liste de stations avec un temps uniforme entre elles (sur une route) -->
	<xs:element name="Section">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SectionStationsList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ID" type="xs:int" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="TimeBetweenStations" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- Une route, avec un id unique, un type et des sections ... -->
	<xs:element name="Route">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element name="ID" type="xs:string"/>
				<xs:element name="Kind">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="High Speed Rail"/>
							<xs:enumeration value="Train"/>
							<xs:enumeration value="Regional Rail"/>
							<xs:enumeration value="Metro"/>
							<xs:enumeration value="Trolley"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="RouteSectionsList">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Section" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Correspondance entre une station sur une ligne et un ensemble de couples Station/Ligne.
          Attention : les correspondances ne sont donnees qu'une fois sans permutations : l'ordre ne compte pas. 
    -->
	<xs:element name="Interchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Start">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Station" type="xs:int"/>
							<xs:element name="Route" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Endlist">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="End">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Station" type="xs:int"/>
										<xs:element name="Route" type="xs:string"/>
										<xs:element name="Free" type="xs:boolean"/>
										<xs:element name="Pedestrian" type="xs:boolean"/>
										<xs:element name="Time" type="xs:byte"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Le reseau consolide tous les autres elements : les services, les stations, les routes et les changements 
          Il declare les cles etrangeres.
    -->
	<xs:element name="Network">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ServicesList">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Service" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="StationsList">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Station" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="RoutesList">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Route" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="InterchangesList">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Interchange" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="ServiceIdKey">
			<xs:selector xpath="ServicesList/Service"/>
			<xs:field xpath="ID"/>
		</xs:unique>
		<xs:unique name="StationIdKey">
			<xs:selector xpath="StationsList/Station"/>
			<xs:field xpath="ID"/>
		</xs:unique>
		<xs:unique name="RouteIdKey">
			<xs:selector xpath="RoutesList/Route"/>
			<xs:field xpath="ID"/>
		</xs:unique>
		<xs:keyref name="StationServicesIdRef" refer="ServiceIdKey">
			<xs:selector xpath="StationsList/Station/StationServicesList/ID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="SectionStationIdRef" refer="StationIdKey">
			<xs:selector xpath="RoutesList/Route/RouteSectionsList/Section/SectionStationsList/ID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="InterchangeStartStationIdRef" refer="StationIdKey">
			<xs:selector xpath="InterchangesList/Interchange/Start"/>
			<xs:field xpath="Station"/>
		</xs:keyref>
		<xs:keyref name="InterchangeStartRouteIdRef" refer="RouteIdKey">
			<xs:selector xpath="InterchangesList/Interchange/Start"/>
			<xs:field xpath="Route"/>
		</xs:keyref>
		<xs:keyref name="InterchangeEndStationIdRef" refer="StationIdKey">
			<xs:selector xpath="InterchangesList/Interchange/Endlist/End"/>
			<xs:field xpath="Station"/>
		</xs:keyref>
		<xs:keyref name="InterchangeEndRouteIdRef" refer="RouteIdKey">
			<xs:selector xpath="InterchangesList/Interchange/Endlist/End"/>
			<xs:field xpath="Route"/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== bryan-brancotte/projetgl-2008/doc/archives/XML/NetworkGL2008.xml
<?xml version="1.0" encoding="UTF-8"?>
<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NetworkGL2008.xsd">
	<!-- ************ Liste des services *********** -->
	<ServicesList>
		<Service>
			<ID>1</ID>
			<ShortDescription> Wheelchair accessible station</ShortDescription>
		</Service>
		<Service>
			<ID>2</ID>
			<ShortDescription> Coffee Break</ShortDescription>
		</Service>
		<Service>
			<ID>3</ID>
			<ShortDescription>Flower shop</ShortDescription>
		</Service>
		<Service>
			<ID>4</ID>
			<ShortDescription>Parking</ShortDescription>
		</Service>
	</ServicesList>
	
		<!-- ************ Liste des services *********** -->

	<StationsList>
		<Station>
			<ID>1</ID>
			<Name>	
     69th Street Terminal
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
				<ID>3</ID>
				<ID>4</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>2</ID>
			<Name>	
     MillBourne
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
				<ID>3</ID>
				<ID>4</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>3</ID>
			<Name>	
     63rd
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>4</ID>
			<Name>	
     60th
      </Name>
			<StationServicesList>
				<ID>1</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>5</ID>
			<Name>	
     56th
      </Name>
			<StationServicesList>
				<ID>1</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>6</ID>
			<Name>	
     52nd
      </Name>
			<StationServicesList>
				<ID>1</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>7</ID>
			<Name>	
     46th
      </Name>
			<StationServicesList>
				<ID>1</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>8</ID>
			<Name>	
     40th
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>9</ID>
			<Name>	
              34th
      </Name>
			<StationServicesList>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>10</ID>
			<Name>	
              30th
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>11</ID>
			<Name>	
              15th
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>12</ID>
			<Name>	
              13th
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>13</ID>
			<Name>	
              11th
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>14</ID>
			<Name>	
              8th
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>15</ID>
			<Name>	
              5th
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>16</ID>
			<Name>	
              2nd
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>17</ID>
			<Name>	
              Spring Garden
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>18</ID>
			<Name>	
              Girard
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>19</ID>
			<Name>	
              Berks
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>20</ID>
			<Name>	
              York-Dauphin
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>21</ID>
			<Name>	
              Huntingdon
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>22</ID>
			<Name>	
              Somerset
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>23</ID>
			<Name>	
              Allegheny
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>24</ID>
			<Name>	
              Tioga
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>25</ID>
			<Name>	
              Erie-Torresdale
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>26</ID>
			<Name>	
              Church
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>27</ID>
			<Name>	
              Margaret-Orthodox
      </Name>
			<StationServicesList>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>28</ID>
			<Name>	
              Frankford Transportation Center
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>29</ID>
			<Name>	
              Pattison
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>30</ID>
			<Name>	
              Oregon
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>31</ID>
			<Name>	
              Snyder
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>32</ID>
			<Name>	
              Tasker-Morris
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>33</ID>
			<Name>	
              Ellsworth-Federal
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>34</ID>
			<Name>	
              Lombard-South
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>35</ID>
			<Name>	
              Walnut-Locust
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>36</ID>
			<Name>	
              City Hall
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>37</ID>
			<Name>	
              Race-Vine
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>38</ID>
			<Name>	
              Spring Garden
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>39</ID>
			<Name>	
              Fairmount
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>40</ID>
			<Name>	
              Girard
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>41</ID>
			<Name>	
              Cecil B Moore
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>42</ID>
			<Name>	
              Susquehanna-Dauphin
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>43</ID>
			<Name>	
              North Philadelphia
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>44</ID>
			<Name>	
              Allegheny
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>45</ID>
			<Name>	
              Erie
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>46</ID>
			<Name>	
              Hunting Park
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>47</ID>
			<Name>	
              Wyoming
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>48</ID>
			<Name>	
              Logan
      </Name>
			<StationServicesList>
				<ID>2</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>49</ID>
			<Name>	
              Olney Transportation Center
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>3</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>50</ID>
			<Name>	
              Fern Rock Transportation Center
      </Name>
			<StationServicesList>
				<ID>1</ID>
				<ID>2</ID>
			</StationServicesList>
		</Station>
		<Station>
			<ID>51</ID>
			<Name>	
              19th
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>52</ID>
			<Name>	
              22th
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>53</ID>
			<Name>	
              33rd
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>54</ID>
			<Name>	
              36th
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>55</ID>
			<Name>	
              37th
      </Name>
			<StationServicesList>
			</StationServicesList>
		</Station>
		<Station>
			<ID>56</ID>
			<Name>	
			40th
      </Name>
			<StationServicesList>
				</StationServicesList>
		</Station>
		<Station>
			<ID>57</ID>
			<Name>	
              Cynwynd
      </Name>
			<StationServicesList>
