=== bryan-brancotte/projetgl-2008/doc/XML/TravelAltertGL2008.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">	<xs:element name="Kind">		<xs:simpleType>			<xs:restriction base="xs:string">				<xs:enumeration value="Problem"/>				<xs:enumeration value="Solution"/>			</xs:restriction>		</xs:simpleType>	</xs:element>	<xs:complexType name="RouteType">		<xs:sequence>			<xs:element name="MSID" type="xs:int"/>			<xs:element name="IDR" type="xs:string"/>			<xs:element ref="Kind"/>			<xs:element name="WarningMsg" type="xs:string"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="RouteListType">		<xs:sequence>			<xs:element name="Route" type="RouteType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="StationType">		<xs:sequence>			<xs:element name="MSID" type="xs:int"/>			<xs:element name="ID" type="xs:int"/>			<xs:element ref="Kind"/>			<xs:element name="WarningMsg" type="xs:string"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="StationRouteType">		<xs:sequence>			<xs:element name="MSID" type="xs:int"/>			<xs:element name="IDS" type="xs:int"/>			<xs:element name="IDR" type="xs:string"/>			<xs:element ref="Kind"/>			<xs:element name="WarningMsg" type="xs:string"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="StationRouteListType">		<xs:sequence>			<xs:element name="StationRoute" type="StationRouteType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="StationsListType">		<xs:sequence>			<xs:element name="Station" type="StationType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:element name="TravelAlert">		<xs:complexType>			<xs:sequence>				<xs:element name="VersionNumber" type="xs:int" nillable="false"/>				<xs:element name="StationsList" type="StationsListType"/>				<xs:element name="StationRouteList" type="StationRouteListType"/>				<xs:element name="RouteList" type="RouteListType"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="VersionNumber" type="xs:byte"/>	<xs:element name="WarningMsg" type="xs:string"/></xs:schema>

=== bryan-brancotte/projetgl-2008/doc/Soutenance/Pierrick/test 9/TravelAltertGL2008.xml
<?xml version="1.0" encoding="UTF-8"?><!--  Les changements de fond du reseau (ajout/suppression de stations/lignes/troncons seront geres par le chargement d'un nouveau reseau complet).Ce document XML decrit les changements temporaires qui contiennent 3 listes :     (1) les stations (toutes lignes confondues),     (2) les stations sur une ligne donnee     (3) les lignes toutes entieres qui sont bloques (Problem) momentanement tant qu'un message de deblocage(Solution) n'a pas ete proposé. Un message d'alerte leur est associe.Une identifiant est associe a chaque probleme (MSID) et chaque solution fait reference au probleme qu'elle regle en utilisant cet identifiant.Un problème restera dans les fichiers mis à jour tant qu'il n'est pas résolu. Une fois une solution diffusée pour ce problème il ne sera plus présent dans les fichiers (y compris dans celui contenant la résolution).Ainsi quand le système se lance il est certain que vous disporez de tous les problèmes en cours, vous n'aurez pas à tenir compte des solutions de ce premier fichier.--><TravelAlert xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TravelAltertGL2008.xsd">	<VersionNumber>16</VersionNumber>	<StationsList>		<Station>			<MSID>110</MSID>			<ID>152</ID>			<Kind>Problem</Kind>			<WarningMsg>Closed for construction</WarningMsg>		</Station>	</StationsList></TravelAlert>

=== bryan-brancotte/projetgl-2008/doc/Soutenance/Pierrick/original/TravelAltertGL2008.xml
<?xml version="1.0" encoding="UTF-8"?><!--  Les changements de fond du reseau (ajout/suppression de stations/lignes/troncons seront geres par le chargement d'un nouveau reseau complet).Ce document XML decrit les changements temporaires qui contiennent 3 listes :     (1) les stations (toutes lignes confondues),     (2) les stations sur une ligne donnee     (3) les lignes toutes entieres qui sont bloques (Problem) momentanement tant qu'un message de deblocage(Solution) n'a pas ete proposé. Un message d'alerte leur est associe.Une identifiant est associe a chaque probleme (MSID) et chaque solution fait reference au probleme qu'elle regle en utilisant cet identifiant.Un problème restera dans les fichiers mis à jour tant qu'il n'est pas résolu. Une fois une solution diffusée pour ce problème il ne sera plus présent dans les fichiers (y compris dans celui contenant la résolution).Ainsi quand le système se lance il est certain que vous disporez de tous les problèmes en cours, vous n'aurez pas à tenir compte des solutions de ce premier fichier.--><TravelAlert xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TravelAltertGL2008.xsd">	<VersionNumber>1</VersionNumber>	<StationsList>		<Station>			<MSID>14</MSID>			<ID>24</ID>			<Kind>Solution</Kind>			<WarningMsg>Regular traffic</WarningMsg>		</Station>		<Station>			<MSID>8</MSID>			<ID>67</ID>			<Kind>Solution</Kind>			<WarningMsg>Regular traffic</WarningMsg>		</Station>	</StationsList>	<StationRouteList>		<StationRoute>			<MSID>34</MSID>			<IDS>50</IDS>			<IDR>BS</IDR>			<Kind>Solution</Kind>			<WarningMsg>Traffic resumed</WarningMsg>		</StationRoute>		<StationRoute>			<MSID>56</MSID>			<IDS>12</IDS>			<IDR>MF</IDR>			<Kind>Solution</Kind>			<WarningMsg>Track renewal work over</WarningMsg>		</StationRoute>	</StationRouteList>	<RouteList>		<Route>			<MSID>19</MSID>			<IDR>R6</IDR>			<Kind>Solution</Kind>			<WarningMsg>Signal renewal work over</WarningMsg>		</Route>	</RouteList></TravelAlert>
